
      REAL one(6,6),two(6,6),three(6,6),four(6,6),five(6,6)
      REAL six(6,6),seven(6,6),eight(6,6),nine(6,6),ten(6,6)
      REAL eleven(6,6),twelve(6,6),thirt(6,6),fourt(6,6),fift(6,6)
      REAL sixt(6,6),sevent(6,6),eightt(6,6),ninet(6,6),twenty(6,6)
      REAL twent1(6,6),twent2(6,6), twent3(6,6)

      COMMON /wws/ one,two,three,four,five,six,seven,eight,nine,ten,     &
     & eleven,twelve,thirt,fourt,fift,sixt,sevent,eightt,ninet,          & 
     & twenty,twent1,twent2,twent3

